// Auto-generated by Work Plan 89 Catalog Generator. DO NOT EDIT DIRECTLY.
// Server-side manifest for Admin Dashboard

export interface DiscoveredDashboardSection {
  id: string;
  titleArabic: string;
  category: string;
  flows: Array<{
    id: string;
    titleArabic: string;
    allowedRoles: readonly string[];
  }>;
}

export const DASHBOARD_SECTIONS: readonly DiscoveredDashboardSection[] = [
  {
    id: 'settings',
    titleArabic: 'قطاع الإعدادات السيادية والإدارة العامة',
    category: 'operations',
    flows: [
      { id: '00.1', titleArabic: 'الملف التعريفي وبيانات الشركة', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.10', titleArabic: 'حوكمة وضبط سياسات إشعارات المنظومة', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.11', titleArabic: 'ربط وإدارة مجموعات تيليجرام للعمليات والإدارة', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.12', titleArabic: 'إدارة المستخدمين وتفويض الأدوار وربط العاملين', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.2', titleArabic: 'إدارة وتكويد المواقع والمشاريع', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.3', titleArabic: 'مصفوفة الأقسام والوظائف ودورات الورديات', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.4', titleArabic: 'الملف الشخصي للمسؤول وإعدادات الحساب', allowedRoles: ["SUPER_ADMIN","FIELD_ADMIN"] },
      { id: '00.5', titleArabic: 'تعيين وتوزيع مدراء ومشرفي المواقع', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.6', titleArabic: 'محاكاة وتقمص الأدوار للمدير العام (Ghost Mode)', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.7', titleArabic: 'وحدة التحقيق الجنائي وسجل الحركات الميدانية', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.8', titleArabic: 'رادار الأداء وسرعة الاستجابة ومراقبة الخدمات', allowedRoles: ["SUPER_ADMIN"] },
      { id: '00.9', titleArabic: 'صمامات التحكم الإداري وحالات الطوارئ والذاكرة', allowedRoles: ["SUPER_ADMIN"] }
    ],
  },
  {
    id: 'workforce',
    titleArabic: 'قطاع الموارد البشرية وشؤون العاملين',
    category: 'operations',
    flows: [
      { id: '01.1', titleArabic: 'تسجيل وتعيين عامل / موظف جديد', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT","EXECUTIVE"] },
      { id: '01.2.D', titleArabic: 'تعديل وتحديث بيانات عامل وحوكمة الموافقات', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT","EXECUTIVE"] },
      { id: '01.4', titleArabic: 'تصدير واستيراد كشوف العمالة المتقدم إكسيل RTL', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT","EXECUTIVE"] },
      { id: '01.5', titleArabic: 'دليل وسجل العاملين الشامل والأرشيف السابق (360°)', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT","EXECUTIVE"] },
      { id: '01.6', titleArabic: 'طلب تعديل وتحديث بيانات العامل ذاتياً', allowedRoles: ["WORKER","SUPER_ADMIN","FIELD_ADMIN"] },
      { id: '01.7', titleArabic: 'محرك طلبات انضمام الزوار والربط المشفر عبر الواتساب', allowedRoles: ["GUEST","SUPER_ADMIN","FIELD_ADMIN","GENERAL_ADMIN"] },
      { id: '01.8', titleArabic: 'إنهاء خدمة عامل ومخالصة وتصفية المستحقات والتحول اللحظي لزائر', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT"] },
      { id: '01.9', titleArabic: 'مؤشر التزام وموثوقية العمال الشامل (NEW-80)', allowedRoles: ["SUPER_ADMIN","GENERAL_ADMIN","FIELD_ADMIN","ACCOUNTANT","EXECUTIVE","WORKER"] }
    ],
  }
];
