// Auto-generated by Work Plan 89 Catalog Generator. DO NOT EDIT DIRECTLY.
// Client-safe navigation manifest (Strict zero-leakage of server DTOs or DB calls)

export interface ClientNavigationItem {
  id: string;
  titleArabic: string;
  module: string;
  category: string;
}

export const CLIENT_NAVIGATION_ITEMS: readonly ClientNavigationItem[] = [
  {
    id: '00.1',
    titleArabic: 'الملف التعريفي وبيانات الشركة',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.10',
    titleArabic: 'حوكمة وضبط سياسات إشعارات المنظومة',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.11',
    titleArabic: 'ربط وإدارة مجموعات تيليجرام للعمليات والإدارة',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.12',
    titleArabic: 'إدارة المستخدمين وتفويض الأدوار وربط العاملين',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.2',
    titleArabic: 'إدارة وتكويد المواقع والمشاريع',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.3',
    titleArabic: 'مصفوفة الأقسام والوظائف ودورات الورديات',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.4',
    titleArabic: 'الملف الشخصي للمسؤول وإعدادات الحساب',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.5',
    titleArabic: 'تعيين وتوزيع مدراء ومشرفي المواقع',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.6',
    titleArabic: 'محاكاة وتقمص الأدوار للمدير العام (Ghost Mode)',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.7',
    titleArabic: 'وحدة التحقيق الجنائي وسجل الحركات الميدانية',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.8',
    titleArabic: 'رادار الأداء وسرعة الاستجابة ومراقبة الخدمات',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '00.9',
    titleArabic: 'صمامات التحكم الإداري وحالات الطوارئ والذاكرة',
    module: 'settings',
    category: 'operations',
  },
  {
    id: '01.1',
    titleArabic: 'تسجيل وتعيين عامل / موظف جديد',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.2.D',
    titleArabic: 'تعديل وتحديث بيانات عامل وحوكمة الموافقات',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.4',
    titleArabic: 'تصدير واستيراد كشوف العمالة المتقدم إكسيل RTL',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.5',
    titleArabic: 'دليل وسجل العاملين الشامل والأرشيف السابق (360°)',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.6',
    titleArabic: 'طلب تعديل وتحديث بيانات العامل ذاتياً',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.7',
    titleArabic: 'محرك طلبات انضمام الزوار والربط المشفر عبر الواتساب',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.8',
    titleArabic: 'إنهاء خدمة عامل ومخالصة وتصفية المستحقات والتحول اللحظي لزائر',
    module: 'workforce',
    category: 'operations',
  },
  {
    id: '01.9',
    titleArabic: 'مؤشر التزام وموثوقية العمال الشامل (NEW-80)',
    module: 'workforce',
    category: 'operations',
  }
];
