/**
 * Monorepo Catalog Generator (Work Plan 89)
 * 
 * Atomically generates immutable registry artifacts under `.generated/catalog/`
 * including bot router bindings, dashboard manifests, and permission maps.
 */

import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { scanMonorepoCatalog, type MonorepoCatalog } from './catalog.js';
import { validateMonorepoCatalog, type CatalogValidationReport } from './validate-catalog.js';

export interface GenerateCatalogResult {
  ok: boolean;
  catalog: MonorepoCatalog;
  report: CatalogValidationReport;
  outputDirectory: string;
  filesGenerated: string[];
}

export function generateCatalogArtifacts(
  root = process.cwd(),
  options: { dryRun?: boolean } = {}
): GenerateCatalogResult {
  const catalog = scanMonorepoCatalog(root);
  const report = validateMonorepoCatalog(catalog, root);

  if (!report.valid) {
    throw new Error(
      `Catalog Validation Failed with ${report.errors.length} error(s):\n` +
        report.errors.map((e) => `  - ${e}`).join('\n')
    );
  }

  const outputDir = join(root, '.generated', 'catalog');
  const filesGenerated: string[] = [];

  if (options.dryRun) {
    return {
      ok: true,
      catalog,
      report,
      outputDirectory: outputDir,
      filesGenerated: [
        'modules.json',
        'flows.json',
        'source-map.json',
        'permissions.json',
        'bot.registry.ts',
        'dashboard.server.ts',
        'dashboard.client.ts',
      ],
    };
  }

  if (!existsSync(outputDir)) {
    mkdirSync(outputDir, { recursive: true });
  }

  // 1. modules.json
  const modulesJson = JSON.stringify(catalog.modules, null, 2) + '\n';
  writeFileSync(join(outputDir, 'modules.json'), modulesJson, 'utf8');
  filesGenerated.push('modules.json');

  // 2. flows.json
  const flowsJson = JSON.stringify(catalog.flows, null, 2) + '\n';
  writeFileSync(join(outputDir, 'flows.json'), flowsJson, 'utf8');
  filesGenerated.push('flows.json');

  // 3. source-map.json
  const sourceMapJson = JSON.stringify(catalog.sourceMap, null, 2) + '\n';
  writeFileSync(join(outputDir, 'source-map.json'), sourceMapJson, 'utf8');
  filesGenerated.push('source-map.json');

  // 4. permissions.json
  const permissionsMap: Record<string, string[]> = {};
  for (const flow of catalog.flows) {
    permissionsMap[flow.id] = [...flow.allowedRoles];
  }
  const permissionsJson = JSON.stringify(permissionsMap, null, 2) + '\n';
  writeFileSync(join(outputDir, 'permissions.json'), permissionsJson, 'utf8');
  filesGenerated.push('permissions.json');

  // 5. bot.registry.ts
  const botRegistryCode = `// Auto-generated by Work Plan 89 Catalog Generator. DO NOT EDIT DIRECTLY.
// Catalog Hash: ${catalog.catalogHash}
// Generated At: ${catalog.generatedAt}

import type { CatalogModuleEntry, CatalogFlowEntry } from '../../tools/modules/catalog.js';

export const CATALOG_HASH = '${catalog.catalogHash}';
export const GENERATED_AT = '${catalog.generatedAt}';

export const AUTODISCOVERED_MODULES: readonly CatalogModuleEntry[] = ${JSON.stringify(catalog.modules, null, 2)} as const;

export const AUTODISCOVERED_FLOWS: readonly CatalogFlowEntry[] = ${JSON.stringify(catalog.flows, null, 2)} as const;

export const MODULE_CALLBACK_PREFIXES: ReadonlyMap<string, string> = new Map([
${catalog.modules
  .flatMap((m) => m.callbackPrefixes.map((p) => `  ['${p}', '${m.id}']`))
  .join(',\n')}
]);
`;
  writeFileSync(join(outputDir, 'bot.registry.ts'), botRegistryCode, 'utf8');
  filesGenerated.push('bot.registry.ts');

  // 6. dashboard.server.ts
  const dashboardServerCode = `// Auto-generated by Work Plan 89 Catalog Generator. DO NOT EDIT DIRECTLY.
// Server-side manifest for Admin Dashboard

export interface DiscoveredDashboardSection {
  id: string;
  titleArabic: string;
  category: string;
  flows: Array<{
    id: string;
    titleArabic: string;
    allowedRoles: readonly string[];
  }>;
}

export const DASHBOARD_SECTIONS: readonly DiscoveredDashboardSection[] = [
${catalog.modules
  .map(
    (m) => `  {
    id: '${m.id}',
    titleArabic: '${m.titleArabic}',
    category: '${m.category}',
    flows: [
${m.flows.map((f) => `      { id: '${f.id}', titleArabic: '${f.titleArabic}', allowedRoles: ${JSON.stringify(f.allowedRoles)} }`).join(',\n')}
    ],
  }`
  )
  .join(',\n')}
];
`;
  writeFileSync(join(outputDir, 'dashboard.server.ts'), dashboardServerCode, 'utf8');
  filesGenerated.push('dashboard.server.ts');

  // 7. dashboard.client.ts
  const dashboardClientCode = `// Auto-generated by Work Plan 89 Catalog Generator. DO NOT EDIT DIRECTLY.
// Client-safe navigation manifest (Strict zero-leakage of server DTOs or DB calls)

export interface ClientNavigationItem {
  id: string;
  titleArabic: string;
  module: string;
  category: string;
}

export const CLIENT_NAVIGATION_ITEMS: readonly ClientNavigationItem[] = [
${catalog.flows
  .filter((f) => f.status === 'active')
  .map(
    (f) => `  {
    id: '${f.id}',
    titleArabic: '${f.titleArabic}',
    module: '${f.module}',
    category: '${f.category}',
  }`
  )
  .join(',\n')}
];
`;
  writeFileSync(join(outputDir, 'dashboard.client.ts'), dashboardClientCode, 'utf8');
  filesGenerated.push('dashboard.client.ts');

  return {
    ok: true,
    catalog,
    report,
    outputDirectory: outputDir,
    filesGenerated,
  };
}
