/**
 * Sovereign Module V2 Scaffolding Generator (Work Plan 89 - Phase P6)
 * 
 * Generates autonomous, isolated V2 module architectures inside `modules/<name>/`.
 * STRICT INVARIANT: ZERO modifications to files outside `modules/<name>/`.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface ScaffoldModuleV2Options {
  name: string;
  titleArabic: string;
  descriptionArabic?: string | undefined;
  category?: string | undefined;
  root?: string | undefined;
}

export interface ScaffoldModuleV2Result {
  ok: boolean;
  moduleDir: string;
  moduleName: string;
  filesCreated: string[];
  error?: string | undefined;
}

export function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

export function scaffoldModuleV2(options: ScaffoldModuleV2Options): ScaffoldModuleV2Result {
  const root = options.root ? resolve(options.root) : process.cwd();
  const name = options.name.trim().toLowerCase();
  const titleArabic = options.titleArabic.trim();
  const descriptionArabic = options.descriptionArabic?.trim() ?? `وحدة ${titleArabic}`;
  const category = options.category ?? 'operations';

  if (!/^[a-z0-9-]+$/.test(name)) {
    return {
      ok: false,
      moduleDir: '',
      moduleName: name,
      filesCreated: [],
      error: `Invalid module name: '${name}'. Must contain only lowercase alphanumeric characters and dashes.`,
    };
  }

  if (!titleArabic) {
    return {
      ok: false,
      moduleDir: '',
      moduleName: name,
      filesCreated: [],
      error: 'Module Arabic title is mandatory.',
    };
  }

  const moduleDir = join(root, 'modules', name);
  if (existsSync(moduleDir)) {
    return {
      ok: false,
      moduleDir,
      moduleName: name,
      filesCreated: [],
      error: `Module directory already exists: ${moduleDir}`,
    };
  }

  const filesCreated: string[] = [];

  // Create subdirectories
  const dirsToCreate = [
    moduleDir,
    join(moduleDir, 'src'),
    join(moduleDir, 'src', 'shared'),
    join(moduleDir, 'src', 'flows'),
    join(moduleDir, 'database'),
    join(moduleDir, 'database', 'migrations'),
    join(moduleDir, 'tests'),
    join(moduleDir, 'docs'),
  ];

  for (const dir of dirsToCreate) {
    mkdirSync(dir, { recursive: true });
  }

  const pascalName = toPascalCase(name);

  // 1. package.json
  const pkgContent = {
    name: `@alsaada/${name}`,
    version: '1.0.0',
    private: true,
    type: 'module',
    main: './dist/index.js',
    types: './dist/index.d.ts',
    scripts: {
      build: 'tsc',
      test: 'vitest run',
    },
    dependencies: {
      '@alsaada/core-components': 'workspace:*',
      '@alsaada/database': 'workspace:*',
      '@alsaada/shared': 'workspace:*',
      '@alsaada/telemetry': 'workspace:*',
      zod: '^4.3.6',
    },
    devDependencies: {
      typescript: '^5.9.3',
      vitest: '^3.0.8',
    },
  };
  const pkgPath = join(moduleDir, 'package.json');
  writeFileSync(pkgPath, JSON.stringify(pkgContent, null, 2) + '\n', 'utf8');
  filesCreated.push('package.json');

  // 2. tsconfig.json
  const tsconfigContent = {
    extends: '../../tsconfig.base.json',
    compilerOptions: {
      outDir: './dist',
      rootDir: './src',
      composite: true,
    },
    include: ['src/**/*', 'tests/**/*'],
    exclude: ['node_modules', 'dist'],
  };
  writeFileSync(join(moduleDir, 'tsconfig.json'), JSON.stringify(tsconfigContent, null, 2) + '\n', 'utf8');
  filesCreated.push('tsconfig.json');

  // 3. module.contract.json (V2 standard)
  const contractContent = {
    schemaVersion: '2.0.0',
    id: name,
    version: '1.0.0',
    coreApiRange: '^2.0.0',
    titleArabic,
    descriptionArabic,
    category,
    status: 'draft',
    entry: 'src/index.ts',
    callbackPrefixes: [`action:${name}:`, `wizard:${name}:`],
    requiredCapabilities: ['storage:attachment'],
    providedCapabilities: [],
    dependencies: [],
    permissions: [`${name}:access`, `${name}:manage`],
    database: {
      schemaFile: 'database/schema.prisma',
      relationsFile: 'database/relations.contract.json',
    },
  };
  writeFileSync(
    join(moduleDir, 'module.contract.json'),
    JSON.stringify(contractContent, null, 2) + '\n',
    'utf8'
  );
  filesCreated.push('module.contract.json');

  // 4. src/index.ts
  const indexContent = `/**
 * Module Entrypoint: ${name}
 * Auto-generated by Work Plan 89 V2 Scaffolder.
 */

export * from './module.register.js';
export * from './shared/services.js';
export * from './shared/permissions.js';
`;
  writeFileSync(join(moduleDir, 'src', 'index.ts'), indexContent, 'utf8');
  filesCreated.push('src/index.ts');

  // 5. src/module.register.ts
  const registerContent = `import type { ModuleDefinitionV2 } from '@alsaada/core-components';

export const MODULE_DEFINITION: ModuleDefinitionV2 = {
  schemaVersion: '2.0.0',
  id: '${name}' as any,
  version: '1.0.0',
  titleArabic: '${titleArabic}',
  descriptionArabic: '${descriptionArabic}',
  category: '${category}',
  status: 'draft',
  requiredCapabilities: ['storage:attachment' as any],
  providedCapabilities: [],
  flows: [],
  callbackPrefixes: ['action:${name}:', 'wizard:${name}:'],
};

export function create${pascalName}AppModule(runtime?: unknown) {
  return {
    ...MODULE_DEFINITION,
    runtime,
  };
}
`;
  writeFileSync(join(moduleDir, 'src', 'module.register.ts'), registerContent, 'utf8');
  filesCreated.push('src/module.register.ts');

  // 6. src/shared/services.ts
  const servicesContent = `/**
 * Shared services for ${name} module.
 */

export class ${pascalName}Service {
  constructor(private readonly runtime?: unknown) {}

  async getModuleHealth(): Promise<{ status: string; uptime: number }> {
    return { status: 'healthy', uptime: process.uptime() };
  }
}
`;
  writeFileSync(join(moduleDir, 'src', 'shared', 'services.ts'), servicesContent, 'utf8');
  filesCreated.push('src/shared/services.ts');

  // 7. src/shared/permissions.ts
  const permissionsContent = `/**
 * Canonical permissions for ${name} module.
 */

export const ${pascalName}Permissions = {
  ACCESS: '${name}:access',
  MANAGE: '${name}:manage',
} as const;
`;
  writeFileSync(join(moduleDir, 'src', 'shared', 'permissions.ts'), permissionsContent, 'utf8');
  filesCreated.push('src/shared/permissions.ts');

  // 8. database/schema.prisma (Draft placeholder)
  const schemaPrismaContent = `// Database Schema Fragment for module: ${name}
// Auto-generated by Work Plan 89 V2 Scaffolder.

// Declare domain models here:
// model ${pascalName}Record {
//   id String @id @default(uuid())
//   createdAt DateTime @default(now())
// }
`;
  writeFileSync(join(moduleDir, 'database', 'schema.prisma'), schemaPrismaContent, 'utf8');
  filesCreated.push('database/schema.prisma');

  // 9. database/relations.contract.json
  writeFileSync(
    join(moduleDir, 'database', 'relations.contract.json'),
    JSON.stringify([], null, 2) + '\n',
    'utf8'
  );
  filesCreated.push('database/relations.contract.json');

  // 10. tests/<name>-module.spec.ts
  const specContent = `import { describe, it, expect } from 'vitest';
import { MODULE_DEFINITION, create${pascalName}AppModule } from '../src/index.js';

describe('Work Plan 89 — Module ${name} Contract & Factory Spec', () => {
  it('instantiates module with status draft and valid V2 metadata', () => {
    expect(MODULE_DEFINITION.id).toBe('${name}');
    expect(MODULE_DEFINITION.titleArabic).toBe('${titleArabic}');
    expect(MODULE_DEFINITION.status).toBe('draft');
    expect(MODULE_DEFINITION.callbackPrefixes).toContain('action:${name}:');

    const appMod = create${pascalName}AppModule();
    expect(appMod.id).toBe('${name}');
  });
});
`;
  writeFileSync(join(moduleDir, 'tests', `${name}-module.spec.ts`), specContent, 'utf8');
  filesCreated.push(`tests/${name}-module.spec.ts`);

  return {
    ok: true,
    moduleDir,
    moduleName: name,
    filesCreated,
  };
}

// CLI execution check
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.length < 2 || args[0] === '--help' || args[0] === '-h') {
    console.log('Usage: pnpm tsx tools/scaffold/scaffold-module-v2.ts <name> <title-arabic>');
    console.log('Example: pnpm tsx tools/scaffold/scaffold-module-v2.ts canteen "إدارة الكانتين والإعاشة"');
    process.exit(args[0] === '--help' ? 0 : 1);
  }

  const name = args[0]!;
  const titleArabic = args.slice(1).join(' ');

  try {
    const res = scaffoldModuleV2({ name, titleArabic });
    if (!res.ok) {
      console.error(`❌ Scaffold failed: ${res.error}`);
      process.exit(1);
    }
    console.log(`✅ Module V2 scaffolded successfully: modules/${res.moduleName}`);
    console.log(`📦 Status: 'draft'`);
    console.log(`🔒 Zero Core Modifications Invariant: ${res.filesCreated.length} files created strictly inside modules/${res.moduleName}/`);
  } catch (err) {
    console.error(`❌ Fatal error:`, err);
    process.exit(1);
  }
}
